# -*- coding: utf-8 -*-
"""gzgc_single_object.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17y1NfvgYVI2DYxCeJg2aeOjY6or3AwNn

## Setup and Imports
"""

import os
import numpy as np
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from PIL import Image
from tqdm.notebook import tqdm
import torch
import huggingface_hub
from huggingface_hub import hf_hub_download
import pycocotools
import pycocotools.mask as mask_utils

"""### CONFIG
Below, we configure variables that will make the rest of the notebook organized and easily reproducible
"""

# CONFIG
SHARD_ID = None # The ID of the shard you are currently working on.
ASSIGNEE = ''  # Your Name
HOME = Path('~').expanduser()
REPO_ID = 'DSAIL-ReID/synthetic-gzgc' # hf repo {user/org}/{dataset_name}
LOCAL_DIR = HOME / 'synthetic-gzgc-local' # a local directory where you will download repo files to, save artifacts to and upload from
IMAGES_ROOT = HOME / 'gzgc/gzgc.coco/images/train2020' # local path to the downloaded dataset images
SEGMENTATIONS_ROOT = HOME # path where you downloaded the segmentations csv's

# check that the path to the images exists and has the number of images we expect
assert IMAGES_ROOT.exists()
assert len(list(IMAGES_ROOT.glob('*.jpg'))) == 4948
assert ASSIGNEE, 'Input your name above under "ASSIGNEE"'
assert SHARD_ID, 'Enter the shard id you are currently working on'

# check that the helper code script can be found and imported successfully
assert os.path.exists('inference.py'), 'helper code not found. Make sure the notebook is in the "notebook" directory in the sam-3d-objects-repo or cd into the directory at the top of the notebook using "%cd"'

# Check that the checkpoints have been downloaded and are in the path the code expects to find them
assert list(Path('../checkpoints/hf').glob('*.ckpt')), 'checkpoints not found. Make sure they are downloaded and in the correct path'

shards_path = hf_hub_download(
    repo_id=REPO_ID,
    filename= 'shards.csv',
    repo_type='dataset',
    local_dir=LOCAL_DIR
)

shards = pd.read_csv(shards_path)

# Filter for the current shard images

curr_shard_df = shards[shards['shard_id']==SHARD_ID].copy()
curr_shard_df

curr_shard_df['filepath'] = curr_shard_df['filename'].apply(lambda x: IMAGES_ROOT / x)
curr_shard_df

# Check that the paths are correct and do exist
assert curr_shard_df['filepath'].apply(os.path.exists).all(), 'Filepaths are not configured correctly'



"""## Load Pre-Computed Segmentations

Previously, we downloaded the pre-computed SAM2 and SAM3 segmentations for our dataset from Google Drive.   
Ideally, we should be manually verifying the segmentations to discard low quality segmentations and selecting the best quality segmentations for each image.
For now, we will just work with SAM3 concept segmentations (prompted using text) since they seem to have the best quality.
"""

df_path  = SEGMENTATIONS_ROOT / 'gzgc-mask-rles-archive-sam3-zebragiraffe-concept.csv'
masks_df = pd.read_csv(df_path)
masks_df['filepath'] = masks_df['filepath'].apply(lambda x: IMAGES_ROOT / Path(x).name)
assert masks_df['filepath'].apply(os.path.exists).all(), 'Check File paths'

print(masks_df.shape)
masks_df.head()

curr_shard_df_ = curr_shard_df.merge(masks_df, how='left', on='filepath')
curr_shard_df_

"""## Filtering Masks Using Simple Size Heuristic"""

## Note some images occur more than once since they have 2 or more zebras
curr_shard_df_['filepath'].value_counts()

many_masks_sample_path = IMAGES_ROOT / '000000000975.jpg'
img = Image.open(many_masks_sample_path)

img.thumbnail((400, 400))
img

many_masks = masks_df[masks_df['filepath'] == many_masks_sample_path]

img = Image.open(many_masks_sample_path)
width, height = img.size

# numpy arrays use (height, width)
concat_mask = np.zeros((height, width))

masks = []

for i, row in tqdm(many_masks.iterrows(), total=len(many_masks)):
    try:
        xmin = int(row['xmin'] * width)
        ymin = int(row['ymin'] * height)

        mask = mask_utils.decode(eval(row['rle']))
        mask_h, mask_w = mask.shape

        # correct indexing order (y, x)
        concat_mask[ymin:ymin+mask_h, xmin:xmin+mask_w] += mask

        masks.append(mask)
    except Exception as e:
        print(e)

# Show overlay image
plt.figure(figsize=(8,6))
plt.imshow(img, alpha=0.5)
plt.imshow(concat_mask, alpha=0.5)
plt.axis("off")
plt.title('Overlay masks')
plt.show()

"""### Filter: Eliminate masks that are too small

As can be seen above, there is an example image from `shard 3` with `30 segmentation instances`. In such a case, most of the animals are likely very far away from the camera view and/or occlude one another; thus would likely generate low quality 3D models.

One way we can automatically filter for segmentations that are likely to be low quality is by checking the size. We can filter out masks that are below a certain threshold e.g. eliminate masks that have a width&/height less than 10% of the image width&/height
"""

# Filter out masks that have relative height/width less than MASK_SIZE_THRESHOLD
MASK_SIZE_THRESHOLD = 0.1
print(f'Number of masks before filtering: {curr_shard_df_.shape[0]}')
mask_size_filter = (curr_shard_df_['w']>MASK_SIZE_THRESHOLD) & (curr_shard_df_['h']>MASK_SIZE_THRESHOLD)
curr_shard_df_ = curr_shard_df_[mask_size_filter].copy()
print(f'Number of masks after eliminating masks with relative height/width < {MASK_SIZE_THRESHOLD} : {curr_shard_df_.shape[0]}')

## Create an index that will uniquely identify each mask (each instance of a zebra in an image)
curr_shard_df_['mask_index'] = curr_shard_df_.groupby('filepath').cumcount() + 1
curr_shard_df_

"""## Inferencing

### Setup
"""

assert torch.cuda.is_available(), 'Cannot find gpu device. Switch to a gpu device (preferably L4 (or higher)) before runing the subsequent code'

import os
import imageio
import uuid
from IPython.display import Image as ImageDisplay
from inference import Inference, ready_gaussian_for_video_rendering, render_video, load_image, load_single_mask, display_image, make_scene, interactive_visualizer

PATH = os.getcwd()
TAG = "hf"
config_path = f"{PATH}/../checkpoints/{TAG}/pipeline.yaml"
inference = Inference(config_path, compile=False)



"""### Loop Through Shard Images and Save Output 3D Models. (Optional: Gifs)"""

## Configure Output Save Paths

gifs_root = LOCAL_DIR / 'renders' / f'shard_{SHARD_ID:03d}'
ply_root = LOCAL_DIR / 'gaussians' / f'shard_{SHARD_ID:03d}'
glb_root = LOCAL_DIR / 'meshes' / f'shard_{SHARD_ID:03d}'

gifs_root.mkdir(parents=True, exist_ok=True)
ply_root.mkdir(parents=True, exist_ok=True)
glb_root.mkdir(parents=True, exist_ok=True)

SAVE_GIF = True

for i, row in tqdm(curr_shard_df_.iterrows(), total=len(curr_shard_df_)):
    # Load image
    image_path = row['filepath']
    image = Image.open(image_path)
    image_arr = np.array(image)

    # Load relative mask
    mask = pycocotools.mask.decode(eval(row['rle']))
    binary_mask = mask > 0

    # Create full image mask
    width, height = image.size
    xmin, ymin = round(row['xmin']*width), round(row['ymin']*height)
    fullmask = np.zeros((height, width))
    fullmask[ymin:ymin+mask.shape[0], xmin:xmin+mask.shape[1]] = mask

    # run model
    output = inference(image_arr, fullmask, seed=42)

    # export gaussian splat (as point cloud)
    output["gs"].save_ply(ply_root / f"{image_path.stem}_{row['mask_index']:03}.ply")

    # export mesh
    output['glb'].export(glb_root / f"{image_path.stem}_{row['mask_index']:03}.glb")

    if SAVE_GIF:
        # render gaussian splat
        scene_gs = make_scene(output)
        scene_gs = ready_gaussian_for_video_rendering(scene_gs)

        video = render_video(
            scene_gs,
            r=1,
            fov=90, #60,
            pitch_deg=15,
            yaw_start_deg=-45,
            resolution=512,
        )["color"]

        # save video as gif
        imageio.mimsave(
            os.path.join(gifs_root / f"{image_path.stem}_{row['mask_index']:03}.gif"),
            video,
            format="GIF",
            duration=1000 / 30,  # default assuming 30fps from the input MP4
            loop=0,  # 0 means loop indefinitely
        )

"""### Visualize Sample Output"""

image_path = row['filepath']
image = Image.open(image_path)

width, height = image.size

fullmask = np.zeros((height, width))

xmin = int(row['xmin'] * width)
ymin = int(row['ymin'] * height)
mask_h, mask_w = mask.shape

fullmask[ymin:ymin+mask_h, xmin:xmin+mask_w] += mask

plt.imshow(image, alpha=0.5)
plt.imshow(fullmask, alpha=0.5)
plt.axis('off')
plt.show()

image_path = row['filepath']
gif_path = os.path.join(gifs_root / f"{image_path.stem}_{row['mask_index']:03}.gif")

gif = Image.open(gif_path)

# Create figure
fig, axes = plt.subplots(2, 4, figsize=(20, 10))

# Flatten axes for easy iteration
axes = axes.flatten()

# Loop through images and plot
for i, ax in enumerate(axes):
    frame_index = int(i*300/360*45)
    gif.seek(frame_index)
    ax.imshow(gif)
    ax.set_title(f'frame {frame_index}')
    ax.axis('off')  # Hide axis

# Adjust spacing
plt.tight_layout()

# Show plot
plt.show()

# Moving Animation. Uncomment the lines below to view the moving animation
# Note that this will quickly blow up your notebook and slow things down. Be careful with it.
# You can run it once for sanity check and then clear cell output

# from IPython.display import Image as ImageDisplay
# ImageDisplay(gif_path)



"""## Push Generated Artifacts to Hugging Face

Now that we have generated sam-3d-objects artifacts for a part of our dataset, we can push them to our Hugging Face Dataset. We will push the `gaussians (.ply)`, `meshes (.glb)` and `renders (.gif)` for the current shard.  

Later on, we will run Deeplabcut inferencing for our renders and push them to Hugging Face as well.
"""

import time
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo
from pathlib import Path
from huggingface_hub import HfApi, CommitOperationAdd, hf_hub_download

def upload_results(repo_id, shard_id, local_dir, assignee, statuses_file, local_shard_cache='~/.current_shard.yaml'):
    # uploads gaussians(.ply), meshes(.glb), renders(.gif), deeplabcut-keypoints(.csv), viewpoint-images(.jpg/.png), viewpoint-graphs(.jpg/.png)
    # Add renderer to the metadata.

    local_dir = Path(local_dir)

    # initialize commit operations
    operations = []

    # Add gaussians to commit operations
    gaussians_dir_path = local_dir / 'gaussians' / f'shard_{shard_id:03d}'
    gaussians = gaussians_dir_path.glob('*.ply')
    # gaussians = list(gaussians_dir_path.glob('*.ply'))
    gaussians_operations = [
        CommitOperationAdd(
            path_in_repo=str(path.relative_to(local_dir)),
            path_or_fileobj=str(path),
        )
        for path in gaussians
    ]
    operations.extend(gaussians_operations)
    print(f'created {len(gaussians_operations)} gaussian operations')

    # Add meshes
    meshes_dir_path = local_dir / 'meshes' / f'shard_{shard_id:03d}'
    meshes = meshes_dir_path.glob('*.glb')
    meshes_operations = [
        CommitOperationAdd(
            path_in_repo=str(path.relative_to(local_dir)),
            path_or_fileobj=str(path),
        )
        for path in meshes
    ]
    operations.extend(meshes_operations)
    print(f'created {len(meshes_operations)} meshes operations')

    # Add renders
    renders_dir_path = local_dir / 'renders' / f'shard_{shard_id:03d}'
    renders = renders_dir_path.glob('*.gif')
    renders_operations = [
        CommitOperationAdd(
            path_in_repo=str(path.relative_to(local_dir)),
            path_or_fileobj=str(path),
        )
        for path in renders
    ]
    operations.extend(renders_operations)
    print(f'created {len(renders_operations)} renders operations')

    # Add deeplabcut results (jsons)
    keypoints_dir_path = local_dir / 'deeplabcut-keypoints' / f'shard_{shard_id:03d}'
    keypoints = keypoints_dir_path.glob('*.json')
    keypoints_operations = [
        CommitOperationAdd(
            path_in_repo=str(path.relative_to(local_dir)),
            path_or_fileobj=str(path),
        )
        for path in keypoints
    ]
    operations.extend(keypoints_operations)
    print(f'created {len(keypoints_operations)} keypoints operations')


    # Update task shard status
    local_statuses_path = hf_hub_download(repo_id=repo_id,
                                          repo_type="dataset",
                                          local_dir=local_dir,
                                          filename=statuses_file)

    statuses_df = pd.read_csv(local_statuses_path)
    statuses_df = statuses_df.set_index('shard_id')
    statuses_df.loc[shard_id, 'status'] = 'completed'

    # Get current time and convert to local timezone
    start_time = time.time()
    time_local = datetime.fromtimestamp(start_time, tz=ZoneInfo("Africa/Nairobi"))
    readable_time_local = time_local.strftime("%Y-%m-%d %H:%M:%S %Z")

    # Update shard status file
    statuses_df.loc[shard_id, 'completion_time'] = readable_time_local
    statuses_df = statuses_df.reset_index()
    statuses_df.to_csv(local_statuses_path, index=False)
    local_statuses_path = Path(local_statuses_path)
    status_update_operation = CommitOperationAdd(
        path_in_repo=str(local_statuses_path.relative_to(local_dir)),
        path_or_fileobj=str(local_statuses_path),
    )
    operations.append(status_update_operation)
    print(f'Number of operations: {len(operations)}')

    # Create commit
    api = HfApi()
    api.create_commit(
        repo_id=repo_id,
        repo_type="dataset",
        operations=operations,
        commit_message=f"upload shard {shard_id} results by {assignee}",
    )

upload_results(repo_id=REPO_ID,
               shard_id=SHARD_ID,
               local_dir=LOCAL_DIR,
               assignee=ASSIGNEE,
               statuses_file='statuses.csv'
              )